### ISSUE TITLE
Unable to perform a backup of a single volume

### ISSUE THREAD

**Issue by kumy** [camptocamp/bivac#256]
Nice to see v2 :) but it lack documentation. I'm currently unable to perform a backup of a single volume.

For testing purpose, I've launched the manager using docker-compose:
```
  bivac:
    image: "camptocamp/bivac"
    command: "manager -v -w my_volume"
    environment:
      BIVAC_SERVER_PSK: "qwerty"
      BIVAC_TARGET_URL: "s3:bivac.xxxxxx/bivac/test"
      AWS_ACCESS_KEY_ID: "xxxxxx"
      AWS_SECRET_ACCESS_KEY: "xxxxxx"
      RESTIC_PASSWORD: "xxxxxx"
      RESTIC_DOCKER_IMAGE: "restic/restic:latest"
      #BIVAC_VOLUMES_WHITELIST: "my_volume"
      BIVAC_ORCHESTRATOR: "docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

Here is the ouput:
```
Recreating docker_bivac_1 ... done
Attaching to docker_bivac_1
bivac_1  | time="2019-02-25T15:41:14Z" level=debug msg="Choosing orchestrator based on configuration..."
bivac_1  | time="2019-02-25T15:41:14Z" level=debug msg="Starting volume manager..."
bivac_1  | time="2019-02-25T15:41:14Z" level=info msg="Listening on 0.0.0.0:8182"
bivac_1  | time="2019-02-25T15:41:14Z" level=debug msg="Starting backup manager..."
bivac_1  | time="2019-02-25T15:41:22Z" level=debug msg="Backing up volume." hostname=heron.xxxxxx volume=my_volume
bivac_1  | time="2019-02-25T15:41:22Z" level=error msg="failed to backup volume: failed to deploy agent: failed to create container: Error response from daemon: invalid mount config for type \"volume\": field Target must not be empty" hostname=heron.xxxxxx try=1 volume=heron.xxxxxx
```

I've tried to force a backup from another shell:
```
# bivac backup my_volume --force -v
Backing up `my_volume'...
ERRO[0000] failed to backup volume: failed to connect to the remote Bivac instance: received wrong status code from the Bivac instance: [500] 500 - Internal server error 

# The server show
bivac_1  | time="2019-02-25T15:58:17Z" level=debug msg="Backup manually requested." hostname=merle.rdpfd.com volume=jira_caches
# But no details on the error 500
```

How can we get more detailed errors? Any link to a WIP fresh documentation?
(Amitiés à @raphink  :wink:)
