### ISSUE TITLE
Automated Backups

### ISSUE THREAD

**Issue by LongJeongS** [camptocamp/bivac#295]
Does bivac support automated backups (i.e. backing up at X hour every day cron style)? And if so, how does it manage the versioning of the volumes? 

I couldn't find any issues or documentations around it, and it appears that if I re-run bivac with the same configuration and volumes, it doesn't seem to upload any volumes the second time around. What is the best practice around automating backups at given intervals?

Any pointers or links to existing documentations around this would be much appreciated. 

here is the compose setup I am using
```
bivac:
    image: "camptocamp/bivac"
    command: "manager -v"
    environment:
      BIVAC_SERVER_PSK: "qwerty"
      BIVAC_TARGET_URL: "s3:s3.amazonaws.com/bucket/directory"
      AWS_ACCESS_KEY_ID: "XXXX"
      AWS_SECRET_ACCESS_KEY: "XXXXXXXXX"
      RESTIC_PASSWORD: "XXXXXX"
      RESTIC_DOCKER_IMAGE: "restic/restic:latest"
      BIVAC_ORCHESTRATOR: "docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
