### ISSUE TITLE
MySQL backups not working

### ISSUE THREAD

**Issue by spacemud** [camptocamp/bivac#324]
Hi folks

I'm having trouble getting MySQL (technically MariaDB) backups to work properly. Bivac describes the backup as successful but when checking the repository, no files are uploaded and the `backups/` directory is empty.

Here is the relevant portion of my `docker-compose.yml`:

```yaml
version: '3'

volumes:
  scriptfiles:
  db:

services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    command:
      - mysqld
      - --innodb-flush-method=O_DSYNC
      - --innodb_use_native_aio=0
      - --bind-address=0.0.0.0
    expose:
      - ${MYSQL_PORT}
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
  bivac:
    image: camptocamp/bivac:latest
    container_name: bivac
    restart: unless-stopped
    environment:
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      BIVAC_VERBOSE: "true"
      BIVAC_SERVER_PSK: "test123"
      BIVAC_TARGET_URL: ${BIVAC_TARGET_URL}
      BIVAC_AGENT_IMAGE: camptocamp/bivac:latest
    command: manager
    ports:
      - "8182:8182"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

Normal data volumes - the `scriptfiles` one, are backed up fine.

Bivac info:
```
root@ced16a51a274:/# bivac info
Build_commit: e49c7a78de2a491a24421cf694a08285b899f341
Build_date: 2019-07-10
Golang_version: go1.12.7
Orchestrator: docker
Version: 2.1.0-5-ge49c7a7
Managed Volumes: 2
Address: 0.0.0.0:8182
```
