### ISSUE TITLE
problems when restoring volumes across instances / machines

### ISSUE THREAD

**Issue by Coster** [camptocamp/bivac#338]
I would like to restore a backup from a bivac instance (computer A) to another machine (computer B).

```yml
version: "3.3"

services:
  bivac:
    image: camptocamp/bivac:latest
    command: manager
    ports:
      - "8182:8182"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      HOSTNAME: machine_a
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      BIVAC_VERBOSE: "true"
      BIVAC_TARGET_URL: ${BIVAC_TARGET_URL}
      BIVAC_SERVER_PSK: ${PSK}
      BIVAC_AGENT_IMAGE: camptocamp/bivac:latest
```
```bash
#check_volumes
docker exec -it dockercamptocamp_bivaclatest_bivac_1 bash
	bivac --server.psk ultimateStrongPassword --remote.address http://machine_a:8182 volumes
#restore_volumes
bivac restore --server.psk ultimateStrongPassword --remote.address http://machine_a:8182 myImpVolume
```
```
Restoring `myImpVolume'...
ID: myImpVolume
Name: myImpVolume
Mountpoint: /var/lib/docker/volumes/myImpVolume/_data
Backup date: 2020-01-22 15:52:19
Backup status: Success
Logs:

restore         [0] restoring <Snapshot 00b4dxxx of [/var/lib/docker/volumes/myImpVolume/_data] at 2020-01-22 13:36:06.143466956 +0000 UTC by root@machine_b> to /var/lib/docker/volumes/myImpVolume/_data/Cj2EyHiEupzXxxxx

snapshots       [0] ...
```

my configuration of the containers (identical on both machines) and the commands i tried.

the goal should be to restore a backup of machine a - which was created on a backblaze instance on machine b.

according to logs everything is ok, but it will not be restored. what is the error? does restore not work correctly?
