### ISSUE TITLE
failed to decode agent output ... illegal base64 data at input byte

### ISSUE THREAD

**Issue by varac** [camptocamp/bivac#350]
We have 2 instances of bivac running. One server is behaving just fine, the other one not.
Most volumes fail to backup like this:

```
root@brix:/etc/docker/compose/bivac# docker-compose exec bivac bivac -v backup unifi_controller                                                                                          
Backing up `unifi_controller'...
ID: unifi_controller
Name: unifi_controller
Mountpoint: /var/lib/docker/volumes/unifi_controller/_data
Backup date: 2020-07-01 19:26:37
Backup status: Unknown
Logs:

        testInit
        init
        backup
        forget
```

In the journal logs I find this:

```
Jul 02 10:49:36 brix docker-compose[28176]: bivac_1  | time="2020-07-02T08:49:36Z" level=error msg="failed to decode agent output of `unifi_controller` : illegal base64 data at input byte 9 -> CONTAINER_PARTIAL_MESSAGE=trueeyJ0eXBlIjoic3VjY2Vzc...
```

The last backup is still from yesterday:

```
root@brix:/etc/docker/compose/bivac# docker-compose exec bivac bivac volumes | grep unifi_controller
unifi_controller                unifi_controller                brix            /var/lib/docker/volumes/unifi_controller/_data                  2020-07-01 19:26:37     Unknown          false
```

Although restic reports a successful backup:

```
root@brix:/etc/docker/compose/bivac# docker-compose exec bivac bivac restic --volume unifi_controller snapshots                                                                          
ID        Time                 Host        Tags        Paths
-----------------------------------------------------------------------------------------------------                                                                                    
accfb509  2020-06-30 22:18:35  brix                    /var/lib/docker/volumes/unifi_controller/_data                                                                                    
417a4f00  2020-07-01 19:26:37  brix                    /var/lib/docker/volumes/unifi_controller/_data                                                                                    
8f9e3888  2020-07-02 08:49:04  brix                    /var/lib/docker/volumes/unifi_controller/_data                                                                                    
-----------------------------------------------------------------------------------------------------                                                                                    
3 snapshots
```

Docker and Debian versions are both the same (docker-ce 19.03.9 and Debian "buster" stable)

Here's the docker-compose file of the server where bivac fails:

```


version: "3.7"

services:
  backup-bivac:
    image: camptocamp/bivac:2.2.0 # <<----
    command: "manager -v"
    environment:
      AZURE_ACCOUNT_NAME: sovartobackups
      AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
      BIVAC_TARGET_URL: azure:backup-by-bivac:/
      RESTIC_PASSWORD: ${BACKUP_PASSPHRASE}
      BIVAC_SERVER_PSK: abc
      BIVAC_AGENT_IMAGE: camptocamp/bivac:2.2.0 # <<----
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

We also tried with the `:latest` docker image in both places unsuccessful.
