### ISSUE TITLE
supplementalGroups Openshift

### ISSUE THREAD

**Issue by leros321** [camptocamp/bivac#379]
Bivac agent is making backups with following securityContext
```
  securityContext:
    fsGroup: 1000880000
    seLinuxOptions:
      level: s0:c30,c5
    seccompProfile:
      type: RuntimeDefault
```
but our pod (in same namespace) is using 
```
  securityContext:
    seLinuxOptions:
      level: s0:c30,c5
    supplementalGroups:
    - 65534
```
so, target files has different file permissions and Bivac manager shows errors during file transfer
e.g. **Err:13 cannot access files**

Is it possible to implement `supplementalGroups` in Bivac agent?
