### ISSUE TITLE
Forwarding manager annotations to agent breaks agent network configuration on openshift

### ISSUE THREAD

**Issue by Vampouille** [camptocamp/bivac#386]
Currently all annotations of the manager are copied to the agent Pod. When running on Openshift, the network configuration is stored in the pod annotations:
```yaml
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.158.6.66/23"],"mac_address":"ce:58:ff:83:ba:18","gateway_ips":["10.158.6.1"[],"ip_address":"10.158.6.66/23","gateway_ip":"10.158.6.1"}}'
```
When this annotations is copied to a pod running on another node, this new pod cannot use the gateway and cannot contact the dns service for example. Without dns resolution the agent cannot contact the manager.

We should not copy annotations or filter annotations forwarded to the agent: 
https://github.com/camptocamp/bivac/blob/master/pkg/orchestrators/kubernetes.go#L220
